const fs = require("fs"), vm = require("vm"), assert = require("assert");
const code = fs.readFileSync(require("path").join(__dirname, "..", "Model.js"), "utf8").replace(".pragma library", "");
const model = {}; vm.createContext(model); vm.runInContext(code, model);
assert.deepStrictEqual(JSON.parse(JSON.stringify(model.candidates({Self:{Online:true,DNSName:"one.ts.net.",ID:"1"},Peer:{a:{Online:true,DNSName:"two.ts.net.",StableID:"2"},b:{Online:false,DNSName:"no.ts.net",ID:"3"}}}))), [{id:"1",dns:"one.ts.net",name:"one.ts.net"},{id:"2",dns:"two.ts.net",name:"two.ts.net"}]);
const summary = {product:"gravedecay",api_version:1,node:{platform:"linux"},resources:{},activity:{},health:{},links:{dashboard:"/grave/"}};
assert(model.summary(JSON.stringify(summary)));
assert.equal(model.summary('{"product":"nope"}'), null);
assert.equal(model.safeDnsName("grave.tailnet.ts.net."), "grave.tailnet.ts.net");
assert.equal(model.safeDnsName("grave.ts.net@evil.example"), "");
assert.equal(model.safeDnsName("https://evil.example"), "");
assert.equal(model.safePath("/grave/"), "/grave/");
assert.equal(model.safePath("//evil.example"), "");
assert.equal(model.safePath("/\\evil"), "");
assert.equal(model.safePath("/grave/../term"), "");
const mac = {id:"mac",dns:"mac.ts.net",name:"Mac",summary,lastSeen:1000,reachable:true};
const vmPlot = {id:"vm",dns:"vm.ts.net",name:"VM",summary,lastSeen:2000,reachable:true};
const saved = model.restore(JSON.stringify({nodes:[mac,vmPlot,mac]}));
assert.equal(saved.length, 2);
assert(saved.every(n=>!n.reachable));
const merged = model.merge(saved,[vmPlot]);
assert.equal(merged.length,2);
assert.equal(merged.find(n=>n.id==='mac').reachable,false);
assert.equal(merged.find(n=>n.id==='vm').reachable,true);
assert.equal(model.restore(JSON.stringify({nodes:[{...mac,dns:'vm.ts.net@evil.example'}]})).length,0);
assert.equal(model.restore('invalid').length,0);
const cleaned = model.summary(JSON.stringify({...summary,secret:'hidden',links:{terminal:'//evil.example',dashboard:'/grave/'}}));
assert.equal(cleaned.secret,undefined);
assert.equal(cleaned.links.terminal,undefined);
assert.equal(model.setupPath('/grave/'), '/grave/#t3-setup');
for (const value of [undefined, '//evil.example', '/term/', '/grave/?token=secret', '/grave/#token=secret']) {
    assert.equal(model.setupPath(value), '');
    assert.equal(model.summary(JSON.stringify({...summary, links:{t3_setup:value}})).links.t3_setup, undefined);
}
const withSetup = {...mac, summary:{...summary, links:{t3_setup:'/grave/'}}};
assert.equal(model.restore(JSON.stringify({nodes:[withSetup]}))[0].summary.links.t3_setup, '/grave/');
assert.equal(model.accent('MAC.TAIL.TS.NET.'), '#c399ed');
assert.equal(model.accent('vm.tail.ts.net'), '#f194b0');
assert.equal(model.icon('container'), '📦');
const stopped = {...mac, summary:{...summary, health:{t3:'stopped'}}};
assert.equal(model.connection(stopped, false), 'Dashboard reachable · T3 stopped');
assert.equal(model.connection(stopped, true), 'Checking connection…');
assert.equal(model.connection({...stopped, reachable:false}, false), 'Unreachable — check Tailscale or dashboard');
assert.equal(model.connection(mac, false), 'Dashboard reachable · T3 status unknown');
assert.equal(model.summary(JSON.stringify({...summary, health:{t3:'secret'}})).health.t3, 'unknown');
